#ifndef __COMMAND_H__
#define __COMMAND_H__

#define QUIT "QUIT"
#define FIRE "FIRE"
#define ROTATE_LEFT "ROTATE_LEFT"
#define ROTATE_RIGHT "ROTATE_RIGHT"
#define DRIVE_FORWARD "DRIVE_FORWARD"
#define DRIVE_BACK "DRIVE_BACK"
#define STOP_ROTATE "STOP_ROTATE"
#define STOP_DRIVE "STOP_DRIVE"
#define ROTATE_TURRET_XY "ROTATE_TURRET_XY"
#define FIRE_AT_TANK "FIRE_AT_TANK"
#define KILLED_BY "KILLED_BY"
#define BULLET_DEAD "BULLET_DEAD"
#define RESPAWN "RESPAWN"
#define MOVE_ALL "MOVE_ALL"



#endif
